export const diet = [
    "",
    "You can enjoy all kinds of food in moderation! Opt for a well balanced meal with nutrient dense vegetables, good quality proteins such as grass-fed meat and plant based proteins and good fats such as olives and avocados. Eating well 80% of the time and leaving the 20% for indulgence food is recommended.\nNever eat yourself full, stop eating when two-thirds full and remember to chew your food properly for optimal digestion.",
    "Eat warm food and easily digestible food to reduce the burden on your stomach.\nGo easy on iced drinks, including green smoothies or iced fruit juice. Avoid raw and cold food such as salads and sashimi.\nHalf of your total caloric intake should come from grains and legumes, a third from vegetables, and about 15% from fish or meats.\nEat rice, congee and whole grains. Consider adding chinese yam, dates, walnuts, sweet potato, lamb, prawns, leeks and ginger to your diet!",
    "Eat fragrant and pungent flavoured food such as watercress, onion, mustard and horseradish to invigorate qi movement.\nBitter and sour food such as unrefined apple cider vinegar, rice wine and citrus peel can also help regulate or move qi.\nTry mint tea, jasmine tea, chrysanthemum tea, rose tea, citrus tea to relieve stress and calm the mind.",
    "Eat more lean protein from various sources such as fish, meat, poultry, egg and tofu. Dark colored food such as spinach, black beans, black sesame and black rice are good options too.\nEat high iron food, such as red meat, liver, red dates, beets, spinach, apricots, prunes, mulberries along with high vitamin C food. Remember to avoid caffeine to maximize absorption.\nRemember it takes up to 120 days to fully renew the blood so dietary changes must be maintained for a few months.",
    "Eat food that boost your metabolism. Try adding seasonings like onion, garlic, leek, chives, ginger, vinegar, turmeric, saffron, cayenne pepper and chili pepper to move the blood. \nLimit cold foods such as iced water, ice cream and salads.  ",
    "Limit your intake of raw and cold food. Avoid eating food below room temperature.\nAdd spices such as cinnamon, ginger, turmeric, chardamon, star anise and dates as seasoning to your homecook dishes! Choose apricots, longan, cherries and durians as fruit snacks.\nOpt for warming proteins such as lamb, chicken, beef and prawns.",
    "Think of moistening and cooling food in general to clear the heat. Avoid heaty food such as coffee, alcohol, spicy and oily food. \nEat high water content food such as seaweed, tofu, cucumber, watermelon, water chestnut and tomato.\nOpt for lightly sautéed, steamed or boiled food. Soups and stews are great choices too.",
    "Focus on light flavoured, bitter and aromatic food with diuretic function. \nTry Chinese barley, mung bean, asparagus, kelp, pumpkin, alfalfa, water chestnut and bamboo shoot.\nStop eating as soon as hunger is gone and limit the amount of greasy, fatty, and sweet foods.",
    "Focus on light flavoured and cooling foods with diuretic functions.\nTry Chinese barley, mung bean, asparagus, kelp, cucumber, loofah, water chestnut, bamboo shoot, watermelon and bitter gourd.\nCornsilk tea (the silky fibers on top of the corn), valerian, chamomile tea, chlorella and spirulina are great beverage options for you!\nAvoid roasted, grilled and fried meats. Peanuts, highly processed and sugary food, as well as hydrogenated fats such as margarine should be avoided too.",
    "It is best to cut back on common allergy triggering foods such as gluten, dairy, buckwheat, broad bean, hyacinth bean, chili pepper, seafoods and alcohol.\nEat a balanced and nutrition-dense diet filled with wholesome, unprocessed food to boost your immune system. Try adding bone or fish broth, chicken essence tonics,  adaptogen herbs such as astragalus root, holy basil and licorice root to your diet."
]

export const lifestyle = [
    "",
    "Go for a walk after dinner instead of binging on television shows. Opt for Light Intensity Interval Training (LIIT) when you're tired. Or join that High Intensity Interval Training (HIIT) class you've always wanted to try. \nBe in touch with your energy level and do the movements you feel like. Exercise should make you refreshed (and a little tired!) but not exhausted.",
    "Keep your body warm, and avoid physical and mental strains to prevent more depletion of qi.\nSchedule one light cardio movements to your favourite music track everyday and slowly build up your stamina to five tracks.",
    "Make time for stress management practices. Schedule at least five minutes of deep breathing exercise everyday. Remember to take breaks. Don't be too tough on yourself and be mindful of a potential burn out.\nGo for Shinrin-yoku (Forest Bathing) for relaxation, or simply go for a walk in the forest or nature park.",
    "There is a saying in TCM \"40 parts of qi to make 1 part of blood\”. Blood takes more time and nourishment to replenish. \nRemember to balance physical and mental activities with rest. Sleep an extra hour or take a 15 minutes power nap during the day or  after a tough workout.\nLadies, avoid hardcore exercises and get plenty of rest, especially during menstruation and postpartum.",
    "Get your body moving to get the blood circulation going! Once the qi moves, blood will move along with it. \nThere's a saying in TCM \"With free flow, there is no pain; when there's blockage, there is pain.\" \nTry taking hot baths or sauna. Avoid blood donation which can further deplete the qi.",
    "Keep your body warm. Keep your neck, wrist and ankles covered especially in air-conditioned rooms or in cold weather. Use heat packs or hot towels if necessary.\nEnjoy the sunlight whenever you can and make sure you avoid the cold wind.\nTry warming TCM therapies such as fire cupping and moxibustion to promote the meridian flow and expel coldness. ",
    "Take at least a full day off every week to have relax and and unwind.\nAvoid staying in air-conditioned or central heated room all the time. \nSet a timer to work in a 90 minutes bursts, followed by 5-15 minutes break of no screen time.",
    "Engage in regular exercise to sweat it out! You do no need to hit the gym. A fun, at-home, easy 10 minutes workout is a good start.\nWear light loose clothing to keep the body dry. \nIf you live in a tropical country, put your air-conditioning on 'dry mode' for two hours a day to keep the room dry and ventilated.",
    "Engage in regular exercise to sweat it out! You do no need to hit the gym. A fun, at-home, easy 10 minutes workout is a good start.\nWear light loose clothing to keep the body dry. \nIf you live in a tropical country, put your air-conditioning on 'dry mode' for two hours a day to keep the room dry and ventilated.",
    "Write a food journal and note down how you feel or the symptoms you experience after eating them. \nEliminate those items for a month and note down how you feel and if the allergy subsides.\nIt's also important to modify your lifestyle habits according to the seasons. For example, stay indoors to avoid pollen affection in spring, wear a mask and  keep your living environments clean, ventilated and dust free.\nAvoid having carpets and soft-toys around your home.\n"

]