import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="bg-[url('/images/Landing_IMG@2x.png')] bg-cover bg-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.bdmain}>
        <div className='h-screen w-screen'>
          <div className={styles.box}></div>
          <h1 className={styles.bottomtext}>Your journey towards holistic wellbeing.</h1>
          <div className={styles.navbar}>
            <div className={styles.activenav}></div>
            <div className={styles.next}></div>
            <div className={styles.next}></div>
          </div>
        </div>
      </main>

    </div>
  )
}
