import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { useState } from 'react'

function getLandingIMG() {
  const IMG = 0
  return {
    props: {
      IMG
    }
  }
}

function Landing() {
  return (
    <div className="bg-[url('/images/Landing_IMG@2x.png')] bg-cover bg-center">
      <Head>
        <title>Kanpobliss</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.bdmain}>
        <div className='h-screen w-screen'>
          <div className={styles.box}></div>
          <h1 className={styles.bottomtext}>Your journey towards holistic wellbeing.</h1>
        </div>
      </main>
    </div>
  )
}

function Landing1() {
  return (
    <div className="bg-[url('/images/Landing_IMG2.jpg')] bg-cover bg-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.bdmain}>
        <div className='h-screen w-screen'>
          <div className={styles.box}></div>
          <h1 className={styles.bottomtext}>Guided by your personal in-room wellness coach..</h1>
        </div>
      </main>
    </div>
  )
}

function Landing2() {
  return (
    <div className="bg-[url('/images/Landing_IMG3.jpg')] bg-cover bg-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.bdmain}>
        <div className='h-screen w-screen'>
          <div className={styles.box}></div>
          <h1 className={styles.bottomtext}>Explore dining, spa fitness & self-care rituals, curated for your unique goals & needs.</h1>
        </div>
      </main>
    </div>
  )
}

export default function Home() {
  const [Mstate, setMstate] = useState(0);
  return (
    <>
      {Mstate == 0 ? (<Landing />) : Mstate == 1 ? (<Landing1 />) : (<Landing2 />)}
      <div className={styles.navbar}>
        <Link href='/'>
          <a onClick={() => setMstate(0)}>
            <div className={Mstate == 0 ? styles.activenav : styles.next}></div>
          </a>
        </Link>
            
        <Link href='/'>
          <a onClick={() => setMstate(1)}>
            <div className={Mstate == 1 ? styles.activenav : styles.next}></div></a>
        </Link>

        <Link href='/'>
          <a onClick={() => setMstate(2)}>
            <div className={Mstate == 2 ? styles.activenav : styles.next}></div>
          </a>
        </Link>
            
      </div>
    </>
    
    
  )
}
