export const NeedsData = [
    "",
    "\nYour Yin and Yang are well balanced and your vital energy, Qi, is flowing harmoniously throughout your body! In TCM, your body type is called Neutral. \nHowever, Yin and Yang are in constant flux and can be affected by your changing lifestyle and external environment. \nClick on our wellness tips and recommendations to help you maintain your good health and the harmony in your body!",
    "Qi is the life force or vital energy that pulses through everything in the universe. \nIn TCM, your body type is called Qi Deficiency. When Qi is deficient, your immune system is weak, therefore you are more likely to be extra sensitive to environmental changes and also take longer time to recover from illnesses.\nClick on our wellness tips and recommendations to help you get more energy!\n",
    "The free-flowing of Qi is the fundamental to good physical and mental health. This ebb and flow of Qi is mainly controlled by the Liver organ system. \nIn TCM, your body type is called Qi Stagnation. When Liver Qi is blocked or sluggish, your body is less resilient against stressful situations. Exposure to a prolonged period of unmanaged stress may lead to anxiety and depression. For women, Qi stagnation often attributes to irregular period, PMS and even fertility issues. \nClick on our wellness tips and recommendations to help you move Qi freely and ease into your hectic lifestyle!",
    "Blood is a dense and nutritive substance of the body. It is not just confined to the blood vessels, nor does it contain only red and white blood cells.\nIn TCM, your body type is called Blood Deficiency. It means that there is not enough blood volume in circulation and/or the quality of your blood lack nourishment so it cannot carry out important bodily functions. Blood deficiency is often associated with undernourishment, emotional stress, a weak Spleen and blood loss.\nIf blood is deficient for a prolonged period of time, you may be susceptible to anemia which can cause hair loss, fatigue, dizziness, cold intolerance and menstrual issues (in women).\nClick on our wellness tips and recommendations to help you boost your blood!\n",
    "Blood is a dense and nutritive substance of the body. It is not just confined to the blood vessels, nor does it contain only red and white blood cells.\nIn TCM, your body type is called Blood Stagnation. When blood is stagnant, you may be susceptible to pain, bodyache and bleeding problems, due to blockage in the energy channels. Long term bood stagnation can often lead to Qi stagnation which may affect your emotional health.\nClick on our wellness tips and recommendations to help you improve your blood flow!",
    "When your body lack Yang energy, or your body is relatively more Yin, you are prone to cold symptoms. It is as if the burner has run out of coal.\nIn TCM, your body type is called Yang Deficiency. When your Yang is lacking or weak, you are susceptible to health problems such as fatigue, flu, puffiness and diarrhea.  \nClick on our wellness tips and recommendations to help you generate warmth in your body from within!",
    "When the body's Yin energy is depleted, or your Yang is relatively in excess, you tend to experience heat and dry symptoms such as dry eyes, dry mouth, hot flushes, red tongue with thin layer of coating.\nIn TCM, your body type is called Yin Deficiency. When your Yin is deficient, you are susceptible to health problems such as dry skin, night sweats, hot flushes and chronic fatigue. \nClick on our wellness tips and recommendations to help you nourish your Yin!",
    "\nIn TCM, your body type is called Phlegm Damp. Internal dampness is directly due to the impaired Spleen function in transporting fluids. Whereas external dampness is due to humid weather, damp living conditions or damp-producing foods such as cheese, milk and sugar. \nDampness is considered to be the cause or contributing factor for illnesses like high cholesterol, metabolic disorders, brain fog and fibromyalgia.\nClick on our wellness tips and recommendations to help you rejuvenate and clear out the dampness!",
    "\nIn TCM, your body type is called Damp Heat. Internal dampness is directly due to the impaired spleen function in transporting fluids. Whereas external dampness is due to humid weather, damp living conditions or damp-producing foods such as cheese, milk and sugar. \nWhen dampness is not cleared out, it turns into damp heat which can impair the Yin (body fluids), leading to even more complex clinical manifestations. Damp heat is often toxic, commonly characterized by swelling, pain and even pus. Your body type may also be more susceptible to skin problems, ulcers and urinary difficulties.\nClick on our wellness tips and recommendations to help you clear out the dampness and calm down the heat!",
    "In TCM, your body type is called Sensitive. This is caused by a weakness in defensive Qi and body’s inability to deal with pathogens due to imbalances. You are prone to heightened immune reactions that creates ineffective response to external triggers. Your body is easily affected by allergens, climate and seasonal changes. \nBy healing and strengthening the defensive Qi through diet and lifestyle changes, you can avoid further aggravation of common ailments such as nasal congestion, running nose, eczema and asthma.\nClick on our wellness tips and recommendations to help you modulate your defensive Qi!"
]

export const hightlight = [
    "",
    "You have a fit physique, lustrous complexion and hair. You are energetic, optimistic in nature with the ability to manage your mental and emotional stress. You have a healthy appetite and are adaptable to environmental changes.",
    "You are introverted and soft spoken. You often find it hard to shed extra weight or build muscles. You tend to experience fatigue, shortness of breath and sweating and are prone to catching cold or flu.",
    "You have a Type A personality and a multi-tasker. You often bottle up emotions, and feel worrisome or frustration. You find yourself often sighing and frowning. You tend to experience burping and bloating issues and frequently have stuffiness in the chest.",	
    "You tend to be quiet and soft spoken. You often have sallow complexion and have dizzy spells especially when standing up. You tend to have pale lips, dry hair and skin.",
    "You tend to be impatient, short-tempered or forgetful. You likely lack physical movement and feel uncomfortable in cold environments. Your complexion is dull and lusterless and are more prone to scarring and varicose veins.",
    "You tend to be quiet and introvert. You often complain about cold hands and feet, and being sensitive to cold environments. You are always sleepy and tired and are prone to loose stools or diarrhea.", 
    "You are outgoing and impatient. You like to stay up late and lack hydration. You often complain about warm palms and soles of the feet especially towards the end of the day and often experience dry eyes and mouth. The symptoms usually worsens when you are under extreme stress or when you overconsume spicy food or alcohol.",
    "You have a mild temper and patient personality. You tend to get puffy eyes and feel sluggish and heavy especially during rainy days. You may have also noticed a sticky coating on your tongue. These symptoms are likely due to overconsumption of oily and sweet foods. You also lack the motivation to exercise regularly.",
    "You are easily irritated and have a short temper. You often feel hot, have oily skin which is prone to acne and have bitter sticky taste in your mouth. You may have also noticed a layer of yellow coating on your tongue. You likely lack physical movement. Your symptoms tend to worsen when you eat too much fried food, dairy and alcohol.",
    "You are self conscious and may have low self-esteem. You are very sensitive to the environment such as food, scents and pollen which cause sensitive skin, nasal and respiratory issues. You also have tendency to have dairy and gluten intolerance and are prone to autoimmune conditions."
]